version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: bapp_postgres
    ports:
      - "5433:5432"  # exposed to host as 5433
    environment:
      POSTGRES_DB: bapp_db
      POSTGRES_USER: bapp
      POSTGRES_PASSWORD: 123456789
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./bappdat_backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # host:container
    depends_on:
      - postgres
    volumes:
      - ./bappdat_backend:/app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bapp_postgres:5432/bapp_db
      SPRING_DATASOURCE_USERNAME: bapp
      SPRING_DATASOURCE_PASSWORD: 123456789

  frontend:
    build:
      context: ./bappdat_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./bappdat_frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  pgdata:
