version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    container_name: bapp_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: bapp_db
      POSTGRES_USER: bapp
      POSTGRES_PASSWORD: 123456789
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build:
      context: ./bappdat_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./bappdat_frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
volumes:
  pgdata:
